### ISSUE TITLE
Missing method: client.get_recent_blockhash

### ISSUE THREAD

**Issue by unixneo** [bitzlato/ruby-solana#1]
Hi.  Thanks for this gem.

In your README test code, you have this method:

```ruby
client.get_recent_blockhash
```

Which gives error, of course:

```
irb(main):007:0> tx.recent_blockhash = client.get_recent_blockhash
(irb):7:in `<main>': undefined local variable or method `client' for main:Object (NameError)
```

I searched your lib and could not find this method or anything to create the client object.

Did you use the HTTP API from a different gem to create the client object?

Thanks.

**Comment by unixneo** [comment]
FWIW:

This method is only found in your README file:
```
macos$ cd solanatest
macos$ grep -Ril get_recent_blockhash *
vendor/bundle/ruby/3.0.0/bundler/gems/ruby-solana-3c615fb6dae0/README.md
```

**Comment by unloved** [comment]
Hello, this gem implements only transaction encoding\decoding logic and not making any rpc calls. For sending\receiving data from blockchain you have to write your own http request wrapper, heres quick example for recent_block_hash

solana doc: https://docs.solana.com/ru/developing/clients/jsonrpc-api#example-89
ruby implementation using HTTParty gem

class SolanaClient
  include HTTParty
  base_uri 'https://api.testnet.solana.com'

  def get_recent_blockhash
    data = {"jsonrpc":"2.0","id":1, "method":"getRecentBlockhash"}
    headers = { 'Content-Type': 'application/json'}
    result = self.class.post('/', body: data.to_json, headers: headers)
    result['result']['value']['blockhash']
  end
end

client = SolanaClient.new
client.get_recent_blockhash

**Comment by unixneo** [comment]
Thank you @unloved 

You are not unloved anymore :)

**Comment by unixneo** [comment]
One more question.

Do you know why I get this error with `send_transaction`

```ruby
def send_transaction(signed_tx)
          params = []
          params << signed_tx
          data = {"jsonrpc":"2.0","id":1, "method":"sendTransaction", "params":params}
          headers = { 'Content-Type': 'application/json'}
          result = self.class.post('/', body: data.to_json, headers: headers)
          result['result']
        end
```

Error:

```
SIGNED TX Ab2SM/Y9Q+h1n3X6094vA5hd72wId/igPxbqlCDBLr2PzBvq1EsAQkQ8zTA2k0UZpWzPlP87UPFWhMgZ7lpwgQcBAAEDwuVTk+Z+6KS97ZyLQAtO0TjFL1K8fL0vMdwJJYjMZF0ruhdQ0BZZV7W
parse source {"jsonrpc":"2.0","error":{"code":-32602,"message":"InvalidCharacter { character: '/', index: 5 }"},"id":1}
```

Seems it does not like the `/` in the transaction hash?   I guess this is an encoding issue; but I do not know how to fix it.

Sorry, I am very new with Solana.

**Comment by unixneo** [comment]
Thanks again... it was encoding. Thanks again.

```ruby
        def send_transaction(signed_tx)
          params =  
            [
              signed_tx,
              {
                "encoding": "base64"
              }
            ]
          
          puts "PARAMS: #{params.to_json}"
          data = {"jsonrpc":"2.0","id":1, "method":"sendTransaction", "params": params }
          headers = { 'Content-Type': 'application/json'}
          result = self.class.post('/', body: data.to_json, headers: headers)
          result['result']
        end
```
